version: '3'
services: 
    solr:
        container_name: solr
        ports: 
            - "8983:8983"
        depends_on: 
            - rabbitmq
        build:
            dockerfile: Dockerfile
            context: ./solr
        image: customsolr
        networks: 
            - fulltextsearch
    rabbitmq:
        container_name: rabbit
        image: rabbitmq:3-management
        # ports: 
        #     - "15672:15672"
        #     - "5672:5672"
        networks: 
            - fulltextsearch
    restserver:
        container_name: rest
        image: restserver
        environment: 
            - QUEUE_NAME=upload
            - SOLR_ADDRESS=solr
            - RABBIT_ADDRESS=rabbit
            - CORE_NAME=core1
        depends_on: 
            - rabbitmq
        build:
            dockerfile: Dockerfile
            context: ./rest
        ports: 
            - "3001:3001"
        networks: 
            - fulltextsearch
    writeservice:
        container_name: writeservice
        image: writeservice
        environment: 
            - QUEUE_NAME=upload
            - SOLR_ADDRESS=solr
            - RABBIT_ADDRESS=rabbit
            - CORE_NAME=core1
        build:
            dockerfile: Dockerfile
            context: ./write
        networks:
            - fulltextsearch
        depends_on: 
            - rabbitmq
            - solr
    ui:
        container_name: ui
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        networks: 
            - fulltextsearch
networks: 
    fulltextsearch:
        name: fulltextsearch